import React from 'react';
import './globals.css';
import { Inter } from 'next/font/google';
import Navigation from '@/components/Navigation/Navigation';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Users App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <link rel="stylesheet" href="https://bootswatch.com/5/flatly/bootstrap.min.css" />
      </head>
      <body className={inter.className}>
        <Navigation />
        <div className='container p-4'>
          {children}
        </div>
      </body>
    </html>
  );
}
